language: generic
branches:
  only:
  - master
stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push
jobs:
  include:
    - stage: test # Runs terraform plan to preview infra changes
      script: 
        - . ./run-terraform.sh
        - cd run-dir
        - ./terraform init
        - ./terraform fmt
        - ./terraform plan
    - stage: deploy # Applies the terraform changes
      script: 
        - . ./run-terraform.sh
        - cd run-dir
        - ./terraform init
        - ./terraform fmt
        - ./terraform apply -auto-approve
      # The auto-approve flag removes the need for a human to type 'yes' into the
      # command line when terraform apply is run
before_install:
- mkdir credentials
- touch credentials/isomer-google-credentials.json
- openssl aes-256-cbc -K $encrypted_63f297c768a8_key -iv $encrypted_63f297c768a8_iv
  -in isomer-google-credentials.json.enc -out credentials/isomer-google-credentials.json
  -d